require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe AccountsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Account. As you add validations to Account, be sure to
  # adjust the attributes here as well.
  let(:user) { FactoryGirl.create(:user) }
  let(:account) { FactoryGirl.create(:account) }
  let(:invalid_account) { FactoryGirl.build(:invalid_account) }
  let(:current_user) { login_with(user) }
  let(:invalid_user) { login_with(nil) }
  let(:valid_attributes) { FactoryGirl.attributes_for(:account) }
  let(:invalid_attributes) { FactoryGirl.attributes_for(:invalid_account) }

  shared_examples_for "with a logged in user" do

    describe "GET #index", taco: true do #taco is a tag, which can be run with rspec --tag taco
      it "assigns all accounts as @accounts" do
        get :index
        expect(assigns(:accounts)).to eq([account])
      end

      it "renders the index template" do
        get :index
        expect(response).to render_template(:index)
      end
    end

    describe "GET #show" do
      it "assigns the requested account as @account" do
        get :show, {:id => account.to_param}
        expect(assigns(:account)).to eq(account)
      end

      it "renders the show template" do
        get :show, {:id => account.to_param}
        expect(response).to render_template(:show)
      end
    end

    describe "GET #new" do
      it "assigns a new account as @account" do
        get :new
        expect(assigns(:account)).to be_a_new(Account)
      end

      it "renders the new template" do
        get :new
        expect(response).to render_template(:new)
      end
    end

    describe "GET #edit" do
      it "assigns the requested account as @account" do
        get :edit, {:id => account.to_param}
        expect(assigns(:account)).to eq(account)
      end

      it "renders the edit template" do
        get :edit, {:id => account.to_param}
        expect(response).to render_template(:edit)
      end
    end

    describe "POST #create" do
      context "with valid params" do
        it "creates a new Account" do
          expect {
            post :create, {:account => valid_attributes}
          }.to change(Account, :count).by(1)
        end

        it "assigns a newly created account as @account" do
          post :create, {:account => valid_attributes}
          expect(assigns(:account)).to be_a(Account)
          expect(assigns(:account)).to be_persisted
        end

        it "redirects to the created account" do
          post :create, {:account => valid_attributes}
          expect(response).to redirect_to(Account.last)
        end
      end

      context "with invalid params" do
        it "assigns a newly created but unsaved account as @account" do
          post :create, {:account => invalid_attributes}
          expect(assigns(:account)).to be_a_new(Account)
        end

        it "re-renders the 'new' template" do
          post :create, {:account => invalid_attributes}
          expect(response).to render_template("new")
        end
      end
    end

    describe "PUT #update" do
      context "with valid params" do
        let(:new_attributes) { FactoryGirl.attributes_for(:account, name: "newname") }

        it "updates the requested account" do
          put :update, {:id => account.to_param, :account => new_attributes }
          account.reload
          expect(account.name).to eq("newname")
        end

        it "assigns the requested account as @account" do
          put :update, {:id => account.to_param, :account => new_attributes }
          expect(assigns(:account)).to eq(account)
        end

        it "redirects to the account" do
          put :update, {:id => account.to_param, :account => new_attributes }
          expect(response).to redirect_to(account)
        end
      end

      context "with invalid params" do
        it "assigns the account as @account" do
          put :update, {:id => account.to_param, :account => invalid_attributes }
          expect(assigns(:account)).to eq(account)
        end

        it "re-renders the 'edit' template" do
          put :update, {:id => account.to_param, :account => invalid_attributes }
          expect(response).to render_template("edit")
        end
      end
    end

    describe "DELETE #destroy" do
      it "destroys the requested account" do
        expect {
          delete :destroy, {:id => account.to_param}
        }.to change(Account, :count).by(-1)
      end

      it "redirects to the accounts list" do
        delete :destroy, {:id => account.to_param}
        expect(response).to redirect_to(accounts_url)
      end
    end

  end #logged in user shared_example

  shared_examples_for "an invalid user trying to access" do
    describe "GET #index" do
      it "redirects user to sign up page" do
        get :index
        expect(response).to redirect_to(new_user_session_path)
      end
      # it { is_expected.to redirect_to new_user_session_path }
    end

    describe "GET #show" do
      it "redirects user to sign up page" do
        get :show, {:id => account.to_param}
        expect(response).to redirect_to(new_user_session_path)
      end
    end

    describe "GET #new" do
      it "redirects user to sign up page" do
        get :new
        expect(response).to redirect_to(new_user_session_path)
      end
    end

    describe "GET #edit" do
      it "redirects user to sign up page" do
        get :edit, {:id => account.to_param}
        expect(response).to redirect_to(new_user_session_path)
      end
    end


    describe "POST #create" do
      context "with valid params" do
        it "redirects user to sign up page" do
          post :create, {:account => valid_attributes}
          expect(response).to redirect_to(new_user_session_path)
        end
      end

      context "with invalid params" do
        it "redirects user to sign up page" do
          post :create, {:account => invalid_attributes}
          expect(response).to redirect_to(new_user_session_path)
        end
      end
    end

    describe "PUT #update" do
      context "with valid params" do
        let(:new_attributes) { FactoryGirl.attributes_for(:account, name: "newname") }

        it "redirects user to sign up page" do
          put :update, {:id => account.to_param, :account => new_attributes }
          expect(response).to redirect_to(new_user_session_path)
        end
      end

      context "with invalid params" do
        it "redirects user to sign up page" do
          put :update, {:id => account.to_param, :account => invalid_attributes }
          expect(response).to redirect_to(new_user_session_path)
        end
      end
    end

    describe "DELETE #destroy" do
      it "redirects user to sign up page" do
        delete :destroy, {:id => account.to_param}
        expect(response).to redirect_to(new_user_session_path)
      end
    end

  end #invalid user shared examples

  describe "user access" do
    before :each do
      current_user
      # login_with(user)
      account
    end

    it_behaves_like 'with a logged in user'
  end #user access describe

  describe "invalid user access" do
    before :each do
      invalid_user
      # login_with(nil)
      account
    end

    it_behaves_like 'an invalid user trying to access'
  end #user access describe

end
