require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe MembershipsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Membership. As you add validations to Membership, be sure to
  # adjust the attributes here as well.
  let(:user) { FactoryGirl.create(:user) }
  let(:membership) { FactoryGirl.create(:membership) }
  let(:invalid_membership) { FactoryGirl.build(:invalid_membership) }
  let(:current_user) { login_with(user) }
  let(:invalid_user) { login_with(nil) }
  let(:valid_attributes) { FactoryGirl.build(:membership).attributes } #note that attributes_for
  #won't work for this type of join table.
  let(:invalid_attributes) { FactoryGirl.build(:invalid_membership).attributes }
  let(:new_attributes) { FactoryGirl.build(:membership).attributes }

  shared_examples_for "with a logged in user" do

    describe "GET #index" do
      it "assigns all memberships as @memberships" do
        get :index
        expect(assigns(:memberships)).to eq([membership])
      end

      it "renders the index template" do
        get :index
        expect(response).to render_template(:index)
      end
    end

    describe "GET #show" do
      it "assigns the requested membership as @membership" do
        get :show, {:id => membership.to_param}
        expect(assigns(:membership)).to eq(membership)
      end

      it "renders the show template" do
        get :show, {:id => membership.to_param}
        expect(response).to render_template(:show)
      end
    end

    describe "GET #new" do
      it "assigns a new membership as @membership" do
        get :new
        expect(assigns(:membership)).to be_a_new(Membership)
      end

      it "renders the new template" do
        get :new
        expect(response).to render_template(:new)
      end
    end

    describe "GET #edit" do
      it "assigns the requested membership as @membership" do
        get :edit, {:id => membership.to_param}
        expect(assigns(:membership)).to eq(membership)
      end

      it "renders the edit template" do
        get :edit, {:id => membership.to_param}
        expect(response).to render_template(:edit)
      end
    end

    describe "POST #create" do
      context "with valid params" do
        it "creates a new Membership" do
          valid_attributes
          @membership = Membership.new(valid_attributes)
          expect {
            @membership.save
          }.to change(Membership, :count).by(1)
        end

        it "assigns a newly created membership as @membership" do
          post :create, {:membership => valid_attributes}
          expect(assigns(:membership)).to be_a(Membership)
          expect(assigns(:membership)).to be_persisted
        end

        it "redirects to the created membership" do
          post :create, {:membership => valid_attributes}
          expect(response).to redirect_to(Membership.last)
        end
      end

      context "with invalid params" do
        it "assigns a newly created but unsaved membership as @membership" do
          post :create, {:membership => invalid_attributes}
          expect(assigns(:membership)).to be_a_new(Membership)
        end

        it "re-renders the 'new' template" do
          post :create, {:membership => invalid_attributes}
          expect(response).to render_template("new")
        end
      end
    end

    describe "PUT #update" do
      context "with valid params" do

        it "updates the requested membership" do
          put :update, {:id => membership.to_param, :membership => new_attributes }
          membership.reload
          expect(membership.user_id).to eq(new_attributes["user_id"])
        end

        it "assigns the requested membership as @membership" do
          put :update, {:id => membership.to_param, :membership => new_attributes }
          expect(assigns(:membership)).to eq(membership)
        end

        it "redirects to the membership" do
          put :update, {:id => membership.to_param, :membership => new_attributes }
          expect(response).to redirect_to(membership)
        end
      end

      context "with invalid params" do
        it "assigns the membership as @membership" do
          put :update, {:id => membership.to_param, :membership => invalid_attributes }
          expect(assigns(:membership)).to eq(membership)
        end

        it "re-renders the 'edit' template" do
          put :update, {:id => membership.to_param, :membership => invalid_attributes }
          expect(response).to render_template("edit")
        end
      end
    end

    describe "DELETE #destroy" do
      it "destroys the requested membership" do
        expect {
          delete :destroy, {:id => membership.to_param}
        }.to change(Membership, :count).by(-1)
      end

      it "redirects to the memberships list" do
        delete :destroy, {:id => membership.to_param}
        expect(response).to redirect_to(memberships_url)
      end
    end

  end #logged in user shared_example

  shared_examples_for "an invalid user trying to access" do
    describe "GET #index" do
      it "redirects user to sign up page" do
        get :index
        expect(response).to redirect_to(new_user_session_path)
      end
      # it { is_expected.to redirect_to new_user_session_path }
    end

    describe "GET #show" do
      it "redirects user to sign up page" do
        get :show, {:id => membership.to_param}
        expect(response).to redirect_to(new_user_session_path)
      end
    end

    describe "GET #new" do
      it "redirects user to sign up page" do
        get :new
        expect(response).to redirect_to(new_user_session_path)
      end
    end

    describe "GET #edit" do
      it "redirects user to sign up page" do
        get :edit, {:id => membership.to_param}
        expect(response).to redirect_to(new_user_session_path)
      end
    end


    describe "POST #create" do
      context "with valid params" do
        it "redirects user to sign up page" do
          post :create, {:membership => valid_attributes}
          expect(response).to redirect_to(new_user_session_path)
        end
      end

      context "with invalid params" do
        it "redirects user to sign up page" do
          post :create, {:membership => invalid_attributes}
          expect(response).to redirect_to(new_user_session_path)
        end
      end
    end

    describe "PUT #update" do
      context "with valid params" do
        let(:new_attributes) { FactoryGirl.attributes_for(:membership, user_id: "100") }

        it "redirects user to sign up page" do
          put :update, {:id => membership.to_param, :membership => new_attributes }
          expect(response).to redirect_to(new_user_session_path)
        end
      end

      context "with invalid params" do
        it "redirects user to sign up page" do
          put :update, {:id => membership.to_param, :membership => invalid_attributes }
          expect(response).to redirect_to(new_user_session_path)
        end
      end
    end

    describe "DELETE #destroy" do
      it "redirects user to sign up page" do
        delete :destroy, {:id => membership.to_param}
        expect(response).to redirect_to(new_user_session_path)
      end
    end

  end #invalid user shared examples

  describe "user access" do
    before :each do
      membership
      current_user
    end

    it_behaves_like 'with a logged in user'
  end #user access describe

  describe "invalid user access" do
    before :each do
      invalid_user
      membership
    end

    it_behaves_like 'an invalid user trying to access'
  end #user access describe

end
